JOB_TITLE_KEYS = [
                 "IT", "PROGRAMMER", "IDMS", "DATABASE", "CA", "COBOL", "JCL", "MAINFRAME", 
                 "SYSTEMS", "PC", "NETWORK", "DESKTOP", "LINUX", "UNIX", "WINDOWS", "MICROSOFT",
                 "SHAREPOINT", "APPLICATION", "DIGITAL", "IBM"
                 ]

SRC_DATA_URL   = "https://dollarbankcareers.jobs/feed/json"
PROJECT_LINK   = "https://github.com/tekksparrow/dbk-jobs-on-linkedin"
POST_TEMPLATE_P_ONE  =  (
						"Looking for a IT Job?\n"
						"Check out this opportunity at Dollar Bank!\n"
						)

POST_TEMPLATE_P_TWO  =  (
						"\nThis post has been generated by a python script. Interested in the code?\n"
						"The project can be view on github, {}".format(PROJECT_LINK)
						)
					   
					   

PROJECT_LINK   = "https://github.com/tekksparrow/dbk-jobs-on-linkedin"
CLIENT_ID      = ""
CLIENT_SECRET  = "" 
REDIRECT_URI   = "http://localhost:5000/call_review"
CSFR_SECRET    = ""

HOST_SITES_AUTH_URL = {
	"linkedin" : "https://www.linkedin.com/oauth/v2/authorization?",
	"facebook" : "https://www.facebook.com/v3.2/dialog/oauth?"
}
